Fix CI failures due to old flake8
We were using an onld version of flake8 this was causing
TypeError: Flake8Item.__init__() got an unexpected keyword argument 'path'
because of a deprecated pytest feature https://docs.pytest.org/en/stable/deprecations.html#constructors-of-custom-pytest-node-subclasses-should-take-kwargs